import type { Metadata } from 'next'
import styles from './layout.module.scss'
import '@/styles/globals.scss'
import Icon from '@/components/atoms/Icon'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="ja">
            <body className={styles['container']}>
                {/* モバイル用 */}
                {/* <header></header> */}
                <div className={styles['menu-button']}>
                    {/* TODO のちほどmenuアイコンに変更 */}
                    <Icon>三</Icon>
                </div>
                <main>{children}</main>
            </body>
        </html>
    )
}
