import 'ress'
import type { Metadata } from 'next'
import styles from './layout.module.scss'
import '@/styles/globals.scss'
import Footer from '@/components/templates/Footer'
import Header from '@/components/templates/Header'
import classNames from 'classnames'
import { mainFontFace } from '@/utils/font'

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="ja">
            <body className={classNames(styles['container'], mainFontFace.className)}>
                <Header />
                <main>{children}</main>
                <Footer />
            </body>
        </html>
    )
}
